### PR TITLE
Build on ghc 9.2

### LINKED ISSUE #58: Doesn't compile on ghc 9.2 due to another Option instance
https://github.com/haskellari/tree-diff/blob/b52e1e568246895b9ea394444defb9ad6bebd035/src/Data/TreeDiff/Class.hs#L382

produces:

```
src/Data/TreeDiff/Class.hs:382:30: error:
    Not in scope: type constructor or class ‘Semi.Option’
    Module ‘Data.Semigroup’ does not export ‘Option’.
    |
382 | instance ToExpr a => ToExpr (Semi.Option a) where
    |                              ^^^^^^^^^^^

src/Data/TreeDiff/Class.hs:383:13: error:
    Not in scope: data constructor ‘Semi.Option’
    Module ‘Data.Semigroup’ does not export ‘Option’.
    |
383 |     toExpr (Semi.Option x) = App "Option" [toExpr x]
```

### PR DESCRIPTION
**Pull request by danwdart**
Fixes #58.﻿

Still requires overrides for dependencies (jailbreaking) for now so might be worth a revisit when they're updated to ensure the version bounds accept them.

### CODE REVIEW

**Comment by phadej** [comment]
Merged as part of #61, thanks!

**Comment by danwdart** [comment]
Thanks for the merge!
