### ISSUE TITLE
Doesn't compile on ghc 9.2 due to another Option instance

### ISSUE THREAD

**Issue by danwdart** [haskellari/tree-diff#58]
https://github.com/haskellari/tree-diff/blob/b52e1e568246895b9ea394444defb9ad6bebd035/src/Data/TreeDiff/Class.hs#L382

produces:

```
src/Data/TreeDiff/Class.hs:382:30: error:
    Not in scope: type constructor or class ‘Semi.Option’
    Module ‘Data.Semigroup’ does not export ‘Option’.
    |
382 | instance ToExpr a => ToExpr (Semi.Option a) where
    |                              ^^^^^^^^^^^

src/Data/TreeDiff/Class.hs:383:13: error:
    Not in scope: data constructor ‘Semi.Option’
    Module ‘Data.Semigroup’ does not export ‘Option’.
    |
383 |     toExpr (Semi.Option x) = App "Option" [toExpr x]
```

**Comment by RyanGlScott** [comment]
Now that `lens-5.1` is out, I believe all of `tree-diff`'s dependencies can be built with 9.2.1.

**Comment by danwdart** [comment]
I was indeed able to compile, jailbreaking them.

**Comment by RyanGlScott** [comment]
This should be resolved as of [`tree-diff-0.2.1.1`](https://hackage.haskell.org/package/tree-diff-0.2.1.1).

**Comment by phadej** [comment]
@RyanGlScott, indeed. Thanks for reminding about this issue.
